version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app

permissions:
  - object: /var/www/app/scripts/
    pattern: "*.sh"
    mode: 755
hooks:
  BeforeInstall:
   - location: scripts/stop.sh
