version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app

permissions:
  - object: /var/www/app/scripts/
    pattern: "*.sh"
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
    - location: scripts/backup.sh
      runas: root
  AfterInstall:
    - location: scripts/restore.sh
      runas: root
    - location: scripts/start.sh
      runas: root

